Fix error messages

diff --git a/src/fan-config b/src/fan-config
--- a/src/fan-config
+++ b/src/fan-config
@@ -13,7 +13,7 @@ sw_required='echo [ cat printf'
 for i in $sw_required; do
     # software is missing if at least one piece of software is missing
     if ! command -v "$i" > /dev/null; then
-        echo "$0: Required software \"$i\" is missing, installation canceled." >&2
+        echo "$0: Required software \"$i\" is missing, configuration canceled." >&2
         exit 1
     fi
 done
diff --git a/src/uninstall b/src/uninstall
--- a/src/uninstall
+++ b/src/uninstall
@@ -16,7 +16,7 @@ sw_required='echo [ read rm sed'
 for i in $sw_required; do
     # software is missing if at least one piece of software is missing
     if ! command -v "$i" > /dev/null; then
-        echo "$0: Required software \"$i\" is missing, installation canceled." >&2
+        echo "$0: Required software \"$i\" is missing, uninstallation canceled." >&2
         exit 1
     fi
 done
