Add software dependency check to fan-config

diff --git a/src/fan-config b/src/fan-config
--- a/src/fan-config
+++ b/src/fan-config
@@ -8,13 +8,30 @@
 #     $1 - number of seconds to sleep before the fan speed configuration
 #-------------------------------------------------------------------------------
 
+## SOFTWARE DEPENDECIES
+
+sw_missing=0
+# software is missing if at least one piece of software is missing
+$(type echo > /dev/null); ((sw_missing |= $?))
+$(type cat > /dev/null); ((sw_missing |= $?))
+$(type printf > /dev/null); ((sw_missing |= $?))
+$(type sleep > /dev/null); ((sw_missing |= $?))
+
+# check if some software is missing
+if [[ "$sw_missing" -ne 0 ]]; then
+    echo 'Required software is missing, configuration canceled.'
+    exit 1
+fi
+
+## DEFINITIONS
+
 # base address for fan speed configuration
 FAN_SPEED_BASE_ADDR=1335
 
 # array of temperatures (in Celsius) per each fan speed level
 temps=(55 60 62 65 68 72 76 80)
 
-# direct acpi call
+# direct ACPI call
 function acpi_call {
     echo "$*" > /proc/acpi/call
     cat /proc/acpi/call; echo
@@ -35,10 +52,12 @@ function level_temp_set {
     acpi_call "\_SB.PCI0.LPCB.EC0.WRAM 0x$(dec_to_hex $(level_to_addr $1)) 0x$(dec_to_hex $2)"
 }
 
+## EXECUTION
+
 # check "temps" length
 if [ ${#temps[@]} != 8 ]; then
     echo 'Error: length of the "temps" array must be exactly 8.'
-    exit 1
+    exit 2
 fi
 
 # perform sleep before executing
