Update code style
The code now uses standard error stream to report errors. Also a lot of
changes have been applied regarding code style with help of shellcheck
- www.shellcheck.net.

diff --git a/src/fan-config b/src/fan-config
--- a/src/fan-config
+++ b/src/fan-config
@@ -9,14 +9,14 @@
 
 sw_missing=0
 # software is missing if at least one piece of software is missing
-type [ > /dev/null; ((sw_missing |= $?))
-type echo > /dev/null; ((sw_missing |= $?))
-type cat > /dev/null; ((sw_missing |= $?))
-type printf > /dev/null; ((sw_missing |= $?))
+type [ > /dev/null; sw_missing=$((sw_missing | $?))
+type echo > /dev/null; sw_missing=$((sw_missing | $?))
+type cat > /dev/null; sw_missing=$((sw_missing | $?))
+type printf > /dev/null; sw_missing=$((sw_missing | $?))
 
 # check if some software is missing
 if [ "$sw_missing" -ne 0 ]; then
-    echo 'Required software is missing, configuration canceled.'
+    echo "$0: Required software is missing, configuration canceled." >&2
     exit 1
 fi
 
@@ -38,33 +38,33 @@ function acpi_call {
 
 # convert number from decimal to hexadecimal form
 function dec_to_hex {
-    printf '%X' $1
+    printf '%X' "$1"
 }
 
 # get address of each fan speed level
 function level_to_addr {
-    echo $(($FAN_SPEED_BASE_ADDR + $1))
+    echo $((FAN_SPEED_BASE_ADDR + $1))
 }
 
 # assigning fan speed level and temperature
 function level_temp_set {
-    acpi_call '\_SB.PCI0.LPCB.EC0.WRAM '"0x$(dec_to_hex $(level_to_addr $1)) 0x$(dec_to_hex $2)"
+    acpi_call '\_SB.PCI0.LPCB.EC0.WRAM '"0x$(dec_to_hex "$(level_to_addr "$1")") 0x$(dec_to_hex "$2")"
 }
 
 ## EXECUTION
 
 # check "fan_temps" length
 if [ ${#fan_temps[@]} != 8 ]; then
-    echo 'Error: length of the "fan_temps" array must be exactly 8.'
+    echo "$0: Length of the \"fan_temps\" array must be exactly 8." >&2
     exit 2
 fi
 
 # setup each individual fan speed level
-level_temp_set 7 ${fan_temps[7]}
-level_temp_set 6 ${fan_temps[6]}
-level_temp_set 5 ${fan_temps[5]}
-level_temp_set 4 ${fan_temps[4]}
-level_temp_set 3 ${fan_temps[3]}
-level_temp_set 2 ${fan_temps[2]}
-level_temp_set 1 ${fan_temps[1]}
-level_temp_set 0 ${fan_temps[0]}
+level_temp_set 7 "${fan_temps[7]}"
+level_temp_set 6 "${fan_temps[6]}"
+level_temp_set 5 "${fan_temps[5]}"
+level_temp_set 4 "${fan_temps[4]}"
+level_temp_set 3 "${fan_temps[3]}"
+level_temp_set 2 "${fan_temps[2]}"
+level_temp_set 1 "${fan_temps[1]}"
+level_temp_set 0 "${fan_temps[0]}"
diff --git a/src/install b/src/install
--- a/src/install
+++ b/src/install
@@ -12,22 +12,22 @@
 
 sw_missing=0
 # software is missing if at least one piece of software is missing
-type [ > /dev/null; ((sw_missing |= $?))
-type echo > /dev/null; ((sw_missing |= $?))
-type cd > /dev/null; ((sw_missing |= $?))
-type dirname > /dev/null; ((sw_missing |= $?))
-type printf > /dev/null; ((sw_missing |= $?))
-type read > /dev/null; ((sw_missing |= $?))
-type grep > /dev/null; ((sw_missing |= $?))
-type cat > /dev/null; ((sw_missing |= $?))
-type apt > /dev/null; ((sw_missing |= $?))
-type chmod > /dev/null; ((sw_missing |= $?))
-type sed > /dev/null; ((sw_missing |= $?))
-type ln > /dev/null; ((sw_missing |= $?))
+type [ > /dev/null; sw_missing=$((sw_missing | $?))
+type echo > /dev/null; sw_missing=$((sw_missing | $?))
+type cd > /dev/null; sw_missing=$((sw_missing | $?))
+type dirname > /dev/null; sw_missing=$((sw_missing | $?))
+type printf > /dev/null; sw_missing=$((sw_missing | $?))
+type read > /dev/null; sw_missing=$((sw_missing | $?))
+type grep > /dev/null; sw_missing=$((sw_missing | $?))
+type cat > /dev/null; sw_missing=$((sw_missing | $?))
+type apt > /dev/null; sw_missing=$((sw_missing | $?))
+type chmod > /dev/null; sw_missing=$((sw_missing | $?))
+type sed > /dev/null; sw_missing=$((sw_missing | $?))
+type ln > /dev/null; sw_missing=$((sw_missing | $?))
 
 # check if some software is missing
 if [ $sw_missing -ne 0 ]; then
-    echo 'Required software is missing, installation canceled.'
+    echo "$0: Required software is missing, installation canceled." >&2
     exit 1
 fi
 
@@ -35,12 +35,12 @@ fi
 
 # check if running as root
 if [ $EUID -ne 0 ]; then
-    echo 'Please run as root, installation canceled.'
+    echo "$0: Please run as root, installation canceled." >&2
     exit 2
 fi
 
 # change directory to the script directory
-cd -- "$(dirname -- "$0")"
+cd -- "$(dirname -- "$0")" || exit 3
 
 # notice
 echo 'Notice:'
@@ -60,14 +60,14 @@ if [ $jack_config_exist = y ]; then
     echo 'n (already set up)'
     setup_jack=n
 else
-    read setup_jack
+    read -r setup_jack
 fi
 printf '2) Set up the fan speed policy to be less aggressive? [y/n] '
 if [ $fan_config_exist = y ]; then
     echo 'n (already set up)'
     setup_fan=n
 else
-    read setup_fan
+    read -r setup_fan
 fi
 echo
 
@@ -84,7 +84,7 @@ if [ "$setup_fan" = y ]; then echo 'The 2) option will be applied.'; fi
 
 # user confirmation
 echo
-read -p 'Are you really sure to continue? [y/n] ' user_agreed
+read -r -p 'Are you really sure to continue? [y/n] ' user_agreed
 if [ "$user_agreed" != y ]; then
     echo 'Installation canceled.'
     exit
@@ -103,8 +103,8 @@ find_exit_0='^[^#]*exit\(\|\s\s*00*\)\s*\(\|#.*\)$'
 if [ "$setup_jack" = y ]; then
     # check if jack-config file exists
     if [ ! -e jack-config ]; then
-        echo 'The "jack-config" file does not exist, installation canceled.'
-        exit 3
+        echo "$0: The \"jack-config\" file does not exist, installation canceled." >&2
+        exit 4
     else
         # load jack-config file content into variable
         jack_config_string=$(cat jack-config)
@@ -114,8 +114,8 @@ fi
 if [ "$setup_fan" = y ]; then
     # check if fan-config file exists
     if [ ! -e fan-config ]; then
-        echo 'The "fan-config" file does not exist, installation canceled.'
-        exit 4
+        echo "$0: The \"fan-config\" file does not exist, installation canceled." >&2
+        exit 5
     else
         # load fan-config file content into variable
         fan_config_string=$(cat fan-config)
@@ -127,13 +127,12 @@ if [ "$setup_fan" = y ]; then
     # parse user input
     custom_fan_temps_valid=n
     while [ $custom_fan_temps_valid = n ]; do
-        read -p "> " custom_fan_temps
+        read -r -p "> " custom_fan_temps
         if [ -z "$custom_fan_temps" ]; then
             custom_fan_temps_valid=y
         else
             # check if valid temperatures format
-            echo "$custom_fan_temps" | grep -q -e '^[0-9]\+ [0-9]\+ [0-9]\+ [0-9]\+ [0-9]\+ [0-9]\+ [0-9]\+ [0-9]\+$'
-            if [ $? -eq 0 ]; then
+            if echo "$custom_fan_temps" | grep -q -e '^[0-9]\+ [0-9]\+ [0-9]\+ [0-9]\+ [0-9]\+ [0-9]\+ [0-9]\+ [0-9]\+$'; then
                 custom_fan_temps_valid=y
                 # modify the script loaded in the variable to reflect new temperature levels
                 fan_config_string=$(echo "$fan_config_string" | sed -e '/^fan_temps/!b;s/(.*)/('"$custom_fan_temps"')/')
diff --git a/src/uninstall b/src/uninstall
--- a/src/uninstall
+++ b/src/uninstall
@@ -12,15 +12,15 @@
 
 sw_missing=0
 # software is missing if at least one piece of software is missing
-type [ > /dev/null; ((sw_missing |= $?))
-type echo > /dev/null; ((sw_missing |= $?))
-type read > /dev/null; ((sw_missing |= $?))
-type rm > /dev/null; ((sw_missing |= $?))
-type sed > /dev/null; ((sw_missing |= $?))
+type [ > /dev/null; sw_missing=$((sw_missing | $?))
+type echo > /dev/null; sw_missing=$((sw_missing | $?))
+type read > /dev/null; sw_missing=$((sw_missing | $?))
+type rm > /dev/null; sw_missing=$((sw_missing | $?))
+type sed > /dev/null; sw_missing=$((sw_missing | $?))
 
 # check if some software is missing
 if [ $sw_missing -ne 0 ]; then
-    echo 'Required software is missing, uninstallation canceled.'
+    echo "$0: Required software is missing, uninstallation canceled." >&2
     exit 1
 fi
 
@@ -28,7 +28,7 @@ fi
 
 # check if running as root
 if [ $EUID -ne 0 ]; then
-    echo 'Please run as root, uninstallation canceled.'
+    echo "$0: Please run as root, uninstallation canceled." >&2
     exit 2
 fi
 
@@ -38,7 +38,7 @@ fan_config_exist=n; if [ -e "$1/fan-config" ]; then fan_config_exist=y; fi
 
 # check if the program is installed in given installation directory
 if [ $jack_config_exist = n ] && [ $fan_config_exist = n ]; then
-    echo "The program is not installed in given \"$1\" directory, uninstallation canceled."
+    echo "$0: The program is not installed in given \"$1\" directory, uninstallation canceled." >&2
     exit 3
 fi
 
@@ -49,7 +49,7 @@ if [ $fan_config_exist = y ]; then echo 'The fan speed policy will be set to the
 
 # user confirmation
 echo
-read -p 'Are you really sure to continue? [y/n] ' user_agreed
+read -r -p 'Are you really sure to continue? [y/n] ' user_agreed
 if [ "$user_agreed" != y ]; then
     echo 'Uninstallation canceled.'
     exit
